### ISSUE TITLE
Throws error on Gif87a header

### ISSUE THREAD

**Issue by sudsy** [deanm/omggif#10]
Hi There,

A program I am using outputs gif87a format files and although your decoder can read them (I think they are a subset of Gif89a) you have a sanity check that makes sure the header is gif 89a. If I get a chance I can fix this and make a PR. Would you like me to do that or fix it yourself.

Ben

**Comment by deanm** [comment]
Have you tried the change locally?  I believe I didn't include 87a because I was unsure of any subtle differences in the specs

**Comment by sudsy** [comment]
What I did was change the header of my gif to 89a manually and it worked. A
search on Google suggests that 89a is a superset of 87a.

**Comment by deanm** [comment]
3f6bd378340f295fee19db992ce0d337d9e003ee

**Comment by deanm** [comment]
I haven't seen many 87a files, so just curious, which software was outputting 87a?

**Comment by deanm** [comment]
PS: Published in NPM as omggif@1.0.6

**Comment by sudsy** [comment]
A tool called Pixen that I found in the Mac App Store.

Thanks so much for the quick fix. I will be publishing a dependent project
tomorrow which takes an animated gig and outputs it to a grid of LED lights.
