### ISSUE TITLE
Problem with interlaced GIF

### ISSUE THREAD

**Issue by Montoya** [deanm/omggif#12]
This GIF: 
http://giphy.com/gifs/willkim-art-animation-wMymb2jKg27Je

doesn't decode well. It ends up looking like a glitchy mess. I'm just blitting the RGB data to a canvas element and then copying the canvas to images in the DOM. I have no idea what to do differently =/

**Comment by deanm** [comment]
Thanks, very appreciative for the report and test case.  In the name of performance I made the interlacing code a bit tricky, and unfortunately I had just missed a * 4 in one of the calculations.

Fixed in 7763fe847e180dff156a45edfd396085c2135dc3 and pushed to npm as 1.0.8.

Thanks!

**Comment by Montoya** [comment]
Woo, I'm glad it was a simple fix! The GIF is decoding correctly now :)
