### ISSUE TITLE
GifReader error - Unknown GIF block: 0x0

### ISSUE THREAD

**Issue by Montoya** [deanm/omggif#13]
I don't know why this happens but here's the GIF that triggers this error: 
http://media.giphy.com/media/8OfdvDB2F9CUg/giphy-tumblr.gif

I looked in a text editor and the GIF is full of zeros. Tried to modify GifReader so it would ignore those and it complained about the following codes as well: 0xc3, 0x61. No clue =/

**Comment by deanm** [comment]
Yes, I had a look and the file looks quite corrupted.  Maybe the browsers manage to display it but I don't think I will make any changes to omggif for this sort of thing.  Thanks for the report though.
