### ISSUE TITLE
Please add license file

### ISSUE THREAD

**Issue by shadiabuhilal** [deanm/omggif#18]
This package fails on https://www.npmjs.com/package/license-check
other packages are depending of this package, please fix it.

**Comment by abdulhannanali** [comment]
@shadiabuhilal It includes a MIT LICENSE in README.md

**Comment by mootari** [comment]
> other packages are depending of this package, please fix it.

@shadiabuhilal Not really the maintainer's problem, but I imagine he'll happily merge a pull request that adds a license entry to the package.json.
