### ISSUE TITLE
Disposal method 2 not supported

### ISSUE THREAD

**Issue by Oewyn** [deanm/omggif#20]
When disposal method 2 is set, canvas needs to be cleared to the background color before doing the blit operation when using the decodeAndBlitFrame* functions.

example gif / JS attached.
[gif_test.zip](https://github.com/deanm/omggif/files/1250746/gif_test.zip)

**Comment by Oewyn** [comment]
I have a workaround basically by checking the previous frameInfo disposal value and if it's 2 clear the pixel buffer, however i really should be clearing to the indexed background color palette value rather than just assuming it's 0x00000000. I didn't really see an easy way to get to that with the code.

```
    var dispose_last_frame = true;
    for(var i = 0; i < gr.numFrames(); ++i) {
        if(dispose_last_frame) {
            pixel_data.fill(0, 'hex');
            console.log('clearing before frame: ' + i)
        }
        dispose_last_frame = (gr.frameInfo(i).disposal == 2)
        gr.decodeAndBlitFrameRGBA(i, pixel_data);
        frame_data.push(Buffer.from(pixel_data));
    }
```

**Comment by deanm** [comment]
Sorry, maybe it's not clear but decodeAndBlitFrame is not meant to handle the disposal, for example see:

https://github.com/deanm/omggif/blob/master/plask_viewer.js#L30
