### ISSUE TITLE
Are you accepting PRs?

### ISSUE THREAD

**Issue by jtlapp** [deanm/omggif#23]
I have written a GIF animation library using Jimp that supports pluggable encoders and decoders. I made a default codec by wrapping omggif. However, I'm finding problems requiring correction.

Is this repo still active, or should I maintain my own copy of omggif with my library (copying forward your license), as Jimp does?

The errors so far are:
(1) I have an improperly formed GIF that sends omggif into an infinite loop.
(2) omggif should throw instances of Error to capture the stack trace of the code that handed omggif improper data. It currently throws strings.

Thanks for your help. I'm really impressed with this library.

FYI, by necessity, my test suite is becoming a test suite for omggif.

**Comment by deanm** [comment]
Project is alive.  Can you open a bug for 1) and attach the malformed gif?

**Comment by jtlapp** [comment]
Great to hear! I've made about 4 mods to support my GIF library. I've fixed the infinite loop bug and am also catching the case where the provided buffer is too small.

I'd prefer to publish my library before asking for the mods, so you can see the need for them.

Still, I'm extremely impressed with how many GIF variations omggif supports despite not having a test suite! My suite tests quite a bit of it, because I'm using it as my default codec.

So let me get back with you next week.

**Comment by deanm** [comment]
Okay, thanks!  I'm definitely for improving robustness (as long as of course there isn't a performance regression).  If I have to choose between robustness (on invalid input) and performance (on valid input), in omggif's case I will go with the latter.  If it's a wash than obviously robuster is better.  As per the difference of throwing strings or Error, I have to admit this is a topic I will need to do a little bit of reading about.  I've never had problems with stack traces when throwing strings, but realize there will be some programatic differences in terms of not having the properties of the Error object.

**Comment by jtlapp** [comment]
Okay, I've finally posted my GIF library ([`gifwrap`](https://github.com/jtlapp/gifwrap)) and so am ready to provide a PR. I'll post three issues and then a PR for all three. One moment...
