### ISSUE TITLE
Unhelpful exception on exceeding buffer bounds

### ISSUE THREAD

**Issue by jtlapp** [deanm/omggif#25]
During the development of [`gifwrap`](https://github.com/jtlapp/gifwrap), I occasionally provided `omggif` with a buffer that was too small to handle the encoding. It would throw an exception that I found unhelpful and always left me grasping at straws to ID the problem.

I have a PR that detects this situation and throws a meaningful exception.

**Comment by deanm** [comment]
Discussion at https://github.com/deanm/omggif/pull/27#commitcomment-26399174

**Comment by jtlapp** [comment]
Yeah, my claim is a lie. Sorry about that, misremembered the problem. Looks like I'll be ripping this mod out of the PR.

For the record, I was doing buffer management improperly. The proper technique is here: https://github.com/deanm/omggif/pull/27#commitcomment-26401927

Also for the record, @deanm has superhuman patience for devs who are lost in the woods and don't know it.

**Comment by jtlapp** [comment]
@deanm, I think there is a problem writing with a global color table using the new buffer/position setter/getters.

I modified `gifwrap` and ran my tests. I have tests for writing and reading both local and global color table versions of GIFs.

When I use your latest `omggif.js` and provide a huge buffer, all of my tests run fine. But when I provide a buffer that has to scale in size, only the local color table tests work, even though they both run the same frame-writing and buffer-scaling code.

When trying to scale the buffer using a global color table, the encoding completes without error. However, when I try to read it back, I get `GifError: Unknown gif block: 0x0`. Also, my Mac is unable to show it.

I don't have a stripped-down test of encoding/decoding to send you. I'm hoping you have a personal test for this. Mine is intimately tied to `gifwrap`. However, you can see the algorithm here in my revision of a [`_writeFrame()`](https://github.com/jtlapp/gifwrap/blob/master/src/gifcodec.js#L349) function that I use for writing all frames:

```js
        let buffer = gifWriter.getOutputBuffer();
        let startOfFrame = gifWriter.getOutputBufferPosition();
        let bytesWritten;
        let tryAgain = true;

        while (tryAgain) {
            bytesWritten = gifWriter.addFrame(frame.xOffset, frame.yOffset,
                    frame.bitmap.width, frame.bitmap.height, frameInfo.buffer, options);
            tryAgain = false;
            if (bytesWritten >= buffer.length - 1) {
                const biggerBuffer = new Buffer(buffer.length * 1.5);
                buffer.copy(biggerBuffer);
                gifWriter.setOutputBuffer(biggerBuffer);
                gifWriter.setOutputBufferPosition(startOfFrame);
                buffer = biggerBuffer;
                tryAgain = true;
            }
        }
```

The two test cases that fail are [this one](https://github.com/jtlapp/gifwrap/blob/master/test/test_encoding.js#L88) and [the next](https://github.com/jtlapp/gifwrap/blob/master/test/test_encoding.js#L97), which use [this GIF](https://github.com/jtlapp/gifwrap/blob/master/test/fixtures/nburling-public.gif) and [this GIF](https://github.com/jtlapp/gifwrap/blob/master/test/fixtures/rnaples-offsets-public.gif), respectively. Both of these GIFs are officially in the public domain.

I'm still keening for an `omggif` test suite. ;-)

**Comment by jtlapp** [comment]
Okay, figured it out. The initial buffer has to be large enough for the header, including a global color table. My test started at a buffer size of 500 bytes to make sure everything was forced to scale, but that broke the global lookup table tests.

**Comment by jtlapp** [comment]
Okay, I posted a new version of [`gifwrap`](https://github.com/jtlapp/gifwrap) that depends on an external `omggif`. Thank you for so quickly taking care of all of this.

Also, I included tests for [scaling the buffer size](https://github.com/jtlapp/gifwrap/blob/master/test/test_encoding.js#L106), which exercises by my code and yours.
