### ISSUE TITLE
Enumerate public API?

### ISSUE THREAD

**Issue by benwiley4000** [deanm/omggif#28]
Hi, thanks for this great project!

There's no documentation I can see, and although that's ok, it's hard to know which APIs are considered public and which are unstable and possibly changing in a minor or patch semver update.

Which methods are intended to be public?

We are considering exposing the `frameInfo` result in the [`get-pixels`](https://github.com/scijs/get-pixels/pull/42) module.

**Comment by deanm** [comment]
In my opinion omggif isn't really a big enough project to warrant all of this process around semver and whatever else.  Anyway, that said I would not expect the frame info to change, and in the future I could only imagine something would be added, so I think it's okay to assume it is "public".

**Comment by benwiley4000** [comment]
I would disagree at least insofar as get-pixels relies on it and many modules rely on that. Semver is part of the contract we all agree to when we upload modules to npm and disregarding it can have unintended consequences.

That said I understand the task of documentation is huge and possibly not what you signed up for. At least something to the effect of what you said above, in the readme, could be nice for letting folks know what's safe to use. :)

**Comment by deanm** [comment]
I'm not sure we "all agree" to anything because of the NPM package existing.  I am happy to remove the NPM package.
