### ISSUE TITLE
Blending operations in GIFs

### ISSUE THREAD

**Issue by photopea** [deanm/omggif#29]
This is a question about a GIF format in general. 

Let's say I have a transparent background. The first frame has a black letter "L", the second frame has a black letter "I" (at the same place, as the "vertical part" of "L"). 

I would like to represent the second frame as a fully transparent sub-area, that would be copied into a previous frame, and would replace the bottom part of "L":  like "L" - "_" = "I".

It seems like the the sub-area of a new frame is always blended "over" the content (transparent pixel can not replace non-transparent pixel). The only way how to make a pixel transparent again is by disposing it at a previous frame. Am I right? Or is there a way  to copy transparent pixels from the sub-area?

**Comment by deanm** [comment]
From my memory this sounds correct, that the blend mode is always src-over (not copy).

**Comment by photopea** [comment]
oh, ok then.
