### ISSUE TITLE
Supporting corrupted GIFs to some degree

### ISSUE THREAD

**Issue by photopea** [deanm/omggif#40]
There are many gifs out there, which throw "Error: Invalid block size" in this library.

Could we add partial support for corrupted GIFs? The question is "how much corrupted".

I would like the GIF reader to be at least as good as a web browser. I.e. it should be able to recover those frames, which a web browser can recover and play. I believe it should be enough to add just several lines of code, to make GIF reader work with this "type of corruption". What do you think?

Here is an example of a corrupted GIF: 
![IMG_0157](https://user-images.githubusercontent.com/15955558/66403215-7bc88700-e9e6-11e9-85d4-3f4ac3f2e135.gif)

**Comment by deanm** [comment]
I am not sure there is such a standard thing as "a web browser", I am sure there are plenty of bad GIFs that will display in some and not in others. It's mostly probably just a consequence of a bunch of projects sharing the same GIF decoding code.

Anyway, it's a non-goal of omggif to support invalid inputs. Thanks!

**Comment by photopea** [comment]
I completely agree with you, it is a problem of the encoder, which created it, or a medium with a failure, which damaged a file.

But I wanted to get "at least something" out of corrupted GIFs, so I made my own decoder.
