### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by justinmchase** [deanm/omggif#42]
I know you have a permissive license, thanks for that, but would you be willing to put a standard license on this such as MIT? That would help out a lot! Thanks.

**Comment by deanm** [comment]
I don't understand your question. How does the license included with omggif differ from:

https://opensource.org/licenses/MIT

? As far as I can tell omggif is and has always been the word for word MIT license.

**Comment by justinmchase** [comment]
Ok, its pretty close but lacks the literal words "MIT License" I suppose

https://mit-license.org/

So it appears custom even though its verbatim the same, it triggers a legal review.

**Comment by justinmchase** [comment]
Ok I see, I didn't recognize the text specifically as the mit license and I guess I was expecting it to say it right in the text of the license.

**Comment by justinmchase** [comment]
An automated tool I was using may have been triggered by this, I can't remember, but here is an example of how github integration can detect the license type by putting it into a LICENSE file specifically:

https://github.com/electron/electron/blob/main/LICENSE

Which helps tools that do dependency checks know what can be used and what requires legal review.
