### ISSUE TITLE
frame ghosting and partial frames

### ISSUE THREAD

**Issue by thewayur** [deanm/omggif#44]
Hi, i m using omggif lib in ES6,  i am bit familiar about **imagedata** & **disposal** ,

i tried to play with 
`if (frame_num === 0 || frame_info.disposal === 2 /* restore to bg */)`

https://github.com/deanm/omggif/blob/0ec9069a525ec66223eadda3d62059d3685fd3b0/plask_viewer.js#L30

but it is not working well in all gifs, let me explain bit please.

i am referencing two situations

situation 1: clearing imageData for every single frame 

for (let i = 0; index < framesLength; i++) {
imageData = ctx.createImageData(width, height);   // clearing imageData for every single frame i.e. blank data
omggif.decodeAndBlitFrameRGBA(i, imageData.data);
ctx.putImageData(imageData, 0, 0);
}
 
gif1: all frames are fine
![image](https://user-images.githubusercontent.com/2944767/144407885-a362e4d2-a5de-40f2-aa42-ae763921926f.png)

gif2: bad frames:
![image](https://user-images.githubusercontent.com/2944767/144407578-6e8e71f8-2750-4ece-98c4-4ea21bd58eab.png)

gif3: bad frames: 
![image](https://user-images.githubusercontent.com/2944767/144408299-c3a3400c-57c2-41b4-afb2-807dcf23a79c.png)

situation 2: clearing imageData only if disposal===2

for (let i = 0; index < framesLength; i++) {
    if( gif.frameInfo(i).disposal ===2){
	imageData = ctx.createImageData(width, height);   // clearing imageData on disposal ===2 i.e. blank data
  }
omggif.decodeAndBlitFrameRGBA(i, imageData.data);
ctx.putImageData(imageData, 0, 0);
}

gif1: good frames
![image](https://user-images.githubusercontent.com/2944767/144410023-bd8af886-1e20-48a4-b29c-4b03413b881d.png)

gif2: bad frames
![image](https://user-images.githubusercontent.com/2944767/144409909-247fcf29-b57c-47be-8735-de50d9dc11f2.png)

gif3: bad frames
![image](https://user-images.githubusercontent.com/2944767/144410186-99c48670-8e92-468a-9b8d-79730af3c739.png)

need not to mention, if i dont clear imageData at all, every gif produces ghost frames..

please guide me when to clear disposal or canvas or any suitable method.
thank u

![gif1](https://user-images.githubusercontent.com/2944767/144410530-42b52454-476b-4638-be21-cab1d687bea6.gif)
![gif2](https://user-images.githubusercontent.com/2944767/144410539-743dac3a-24b9-4fb0-b479-66d852cdf0c4.gif)
![gif3](https://user-images.githubusercontent.com/2944767/144410547-a652d33b-f108-4f88-bf5b-404f2dfb8f52.gif)

**Comment by deanm** [comment]
omggif's job is to decode and give you the correct information from a gif file, which it is correctly doing here. How you connect that to whatever drawing system you are using is outside the scope of omggif, so unfortunately I don't think I can help you here. You will need to read the GIF spec to make sure you understand how GIFs work and then make sure that you are clearing / repainting the background colour for the appropriate damage rect for the GIF frames. GIF also has a notion of transparency, how to handle all of these things very much depends on the underlying graphics system you are using. The plask viewer script is a few line example that is not at all feature complete with regards to all of these things, it's just a basic demonstration on how to roughly wire up some of the pieces.
