### ISSUE TITLE
gifReader.decodeAndBlitFrameRGBA(frameNumber, pixels) does not work for higher frame

### ISSUE THREAD

**Issue by lhm0** [deanm/omggif#45]
I am lost on the following problem: 

"gifReader.decodeAndBlitFrameRGBA(frameNumber, pixels)" works for the first frames of a gif, but for higher frame numbers, I get only corrupted image data.

**Comment by lhm0** [comment]
The problem was my lack of knowledge about GIF. 

Resolved.

**Comment by sayhicoelho** [comment]
@lhm0 I'm facing the same issue. How did you solve you issue?

**Comment by lhm0** [comment]
when I wrote this, I had not understood how gif works: 

gif frames are incremental - they only show, what has changed compared to the previous frame. This is, why you get the "weird" looking frames. 

So, only the first frame is a complete image. All other frames are incomplete. They are drawn "on top" of the previous image. The way "drawing on top" is done may vary. It depends on the so-called "disposal method", which is defined for every frame. You can find some useful description of disposal methods here: https://legacy.imagemagick.org/Usage/anim_basics/
